% Start Bayesian optimization 
%Start paralell pool if neceshariy
UseParaloll = true ;
if UseParaloll
parpool(4)
end

% Define the optimization variables
% Define the initial point within the bounds of the optimization variables
initialPoint = struct('Tsx_u',2.1151,'Tsy_u',1.1397,'Tsz_u',9,'l0',0.1712,'FaX',0.05,'FaY',0.05,...
                      'Tx',40.3925,'Ty',26.4795,'Tz',450,'X_Gain',55.7683 ,'Y_Gain',12.0128,'Z_Gain',35,...
                      'static_friction_force_z', 10.521,'static_friction_force_y',0.002,'static_friction_force_x',0.002);

% How much is searched around the initial guess
percentage = 25;
multiplierUp = 1 + percentage / 100;
multiplierDown = 1 - percentage / 100;

vars = [optimizableVariable('Tx', [initialPoint.Tx*multiplierDown initialPoint.Tx*multiplierUp]), ...
        optimizableVariable('Tsx_u', [initialPoint.Tsx_u*multiplierDown initialPoint.Tsx_u*multiplierUp]), ...
        optimizableVariable('Y_Gain', [initialPoint.Y_Gain*multiplierDown initialPoint.Y_Gain*multiplierUp]), ...
        optimizableVariable('static_friction_force_y', [initialPoint.static_friction_force_y*multiplierDown initialPoint.static_friction_force_y*multiplierUp]), ...
        optimizableVariable('Ty', [initialPoint.Ty*multiplierDown initialPoint.Ty*multiplierUp]), ...
        optimizableVariable('Tsy_u', [initialPoint.Tsy_u*multiplierDown initialPoint.Tsy_u*multiplierUp]), ...
        optimizableVariable('X_Gain', [initialPoint.X_Gain*multiplierDown initialPoint.X_Gain*multiplierUp]), ...
        optimizableVariable('static_friction_force_x', [initialPoint.static_friction_force_x*multiplierDown initialPoint.static_friction_force_x*multiplierUp]), ...
        optimizableVariable('Tz', [initialPoint.Tz*multiplierDown initialPoint.Tz*multiplierUp]), ...
        optimizableVariable('Tsz_u', [initialPoint.Tsz_u*multiplierDown initialPoint.Tsz_u*multiplierUp]), ...
        optimizableVariable('Z_Gain', [initialPoint.Z_Gain*multiplierDown initialPoint.Z_Gain*multiplierUp]), ...
        optimizableVariable('static_friction_force_z', [initialPoint.static_friction_force_z*multiplierDown initialPoint.static_friction_force_z*multiplierUp]), ...
        optimizableVariable('FaX', [initialPoint.FaX*multiplierDown initialPoint.FaX*multiplierUp]), ...
        optimizableVariable('FaY', [initialPoint.FaY*multiplierDown initialPoint.FaY*multiplierUp]), ...
        optimizableVariable('l0', [initialPoint.l0*multiplierDown initialPoint.l0*multiplierUp])];


% Run optimization 
numIterations = 5000;

results = bayesopt(@(params)objective(params), vars, ...
    'MaxObjectiveEvaluations', numIterations, ...
    'AcquisitionFunctionName', 'expected-improvement', ...
    'UseParallel', UseParaloll, ...
    'IsObjectiveDeterministic', true, ...
    'InitialX',struct2table(initialPoint));